// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['main']['App']['Close']();
}

export function FetchCar(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['FetchCar'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function FetchPed(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['FetchPed'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function FetchTL(arg1, arg2) {
  return window['go']['main']['App']['FetchTL'](arg1, arg2);
}

export function Open() {
  return window['go']['main']['App']['Open']();
}
