// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Close():Promise<void>;

export function FetchCar(arg1:number,arg2:number,arg3:number,arg4:number,arg5:number,arg6:number):Promise<main.FetchCarReturn>;

export function FetchPed(arg1:number,arg2:number,arg3:number,arg4:number,arg5:number,arg6:number):Promise<main.FetchPedReturn>;

export function FetchTL(arg1:number,arg2:number):Promise<main.FetchTLReturn>;

export function Open():Promise<main.LoadReturn>;
